# SMIB system as in Milano's book example 8.1

In [1]:
%matplotlib widget

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sopt
import ipywidgets
from pydae import ssa
import json
from IPython.display import SVG

In [3]:
#SVG('smib_milano_ex8p1_4ord_api.svg')

## Import system module

In [4]:
from iso_milano_ex8p1_4ord_uctrl import iso_milano_ex8p1_4ord_uctrl_class

## Instantiate system

In [5]:
syst = iso_milano_ex8p1_4ord_uctrl_class()

## Initialize the system (backward and foreward)

In [10]:
events=[{'p_l':0,'q_l':0,'D':0.01,'K_delta':0.1, 'v_t':1.0}]
syst.initialize(events,xy0=1.0)

syst.report_x()
syst.report_y()

delta =  1.00
omega =  1.00
e1q   =  1.00
e1d   =  0.00
i_d   = -0.00
i_q   =  0.00
p_t   = -0.00
q_t   =  0.00
v_t   =  1.00
theta_t =  1.00
v_0   =  1.00
theta_0 =  1.00


In [7]:
syst.get_value('q_t')

-0.08044839430974793

## Run in two time intervals

In [8]:
events=[{'t_end':1.0}]
syst.run(events)
events=[{'t_end':2.0}]
syst.run(events)

1

In [9]:
syst.get_value('omega')

0.9999983614804228

In [10]:
syst.set_value('p_m', 0.0)

In [11]:
syst.get_value('p_m')

1.0

In [31]:
syst = iso_milano_ex8p1_4ord_uctrl_class()

events=[{'p_l':0.0,'q_l':0.0,'D':0.1}]
syst.initialize(events,xy0=1)

events=[{'t_end':1},
        {'t_end':2.0, 'p_l':0.1,'q_l':0.0}
       ]

syst.simulate(events,xy0=1);

In [32]:
plt.close('all')
fig, axes = plt.subplots(nrows=2,ncols=2, figsize=(10, 5), frameon=False, dpi=70)

axes[0,0].plot(syst.T, syst.get_values('omega')-1, label=f'$\omega$')
axes[0,1].plot(syst.T, syst.get_values('v_t'),   label=f'$v_t$')
axes[1,0].plot(syst.T, syst.get_values('p_t'),   label=f'$p_t$')
axes[1,1].plot(syst.T, syst.get_values('q_t'),   label=f'$q_t$')

for ax in axes.flatten(): 
    ax.legend()
    ax.grid(True)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [32]:
1/(3.49-2.87)
0.0014*0.37
2.158


0.000518

In [31]:
Δt = 0.01
times = np.arange(0.0,10,Δt)

# Calculate initial references
events=[{'p_l':0,'q_l':0,'D':0.01,'K_delta':0.1,'K_v':1e-3, 'v_t':1.0}]
syst.initialize(events,xy0=1.0)

v_t_0 = syst.get_value('v_t')
v_f_0 = syst.get_value('v_f')
p_m_0 = syst.get_value('p_m')
omega_0 = syst.get_value('omega')

K = 100.0
Droop = 0.05

v_t = v_t_0
omega = omega_0
p_t = p_t_0
for t in times:
    
    v_t_ref = v_t_0 

    p_l = 0.0
    if t>1.0: 
        p_l = 0.7 
    q_l = 0.0
    if t>3.0: 
        q_l = 0.2 
        
    syst.set_value('p_l',p_l) 
    syst.set_value('q_l',q_l) 
    
    p_m = 1/Droop*(omega_0-omega) + p_m_0
    v_f = K*(v_t_ref - v_t) + v_f_0 
        
    v_t = syst.get_value('v_t')
    omega = syst.get_value('omega')
        
    events=[{'t_end':t,'v_f':v_f,'p_m':p_m}]
    syst.run(events)

syst.post();
    
    
    

In [11]:
syst = iso_milano_ex8p1_4ord_uctrl_class()


events=[{'p_l':0.0,'q_l':0.0}]
syst.initialize(events,xy0=1)
ssa.eval_A(syst)
ssa.damp_report(syst)

C:\Users\jmmau\anaconda3\lib\site-packages\pydae\ssa.py:107: RuntimeWarning: invalid value encountered in true_divide
  zetas = -sigmas/np.sqrt(sigmas**2+omegas**2)


Real  Imag  Freq.  Damp
Mode 1 -0.001000   0.0    0.0   1.0
Mode 2 -0.000000   0.0    0.0   NaN
Mode 3 -0.755891   0.0    0.0   1.0
Mode 4 -2.705289   0.0    0.0   1.0

In [33]:
1/np.abs(-0.519881)

1.923517112569992

In [43]:
1/0.398968

2.5064666840448355

In [42]:
1/(2*np.pi*0.034458)

4.618809654997253

In [41]:
0.001274*0.37

0.00047138

In [32]:
plt.close('all')
fig, axes = plt.subplots(nrows=2,ncols=2, figsize=(10, 5), frameon=False, dpi=70)

axes[0,0].plot(syst.T, syst.get_values('omega')-1, label=f'$\omega$')
axes[0,1].plot(syst.T, syst.get_values('v_t'),   label=f'$v_t$')
axes[1,0].plot(syst.T, syst.get_values('p_t'),   label=f'$p_t$')
axes[1,1].plot(syst.T, syst.get_values('q_t'),   label=f'$q_t$')

for ax in axes.flatten(): 
    ax.legend()
    ax.grid(True)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [21]:


v_t_0   = syst.struct[0]['v_t']
v_f_ref = syst.struct[0]['v_f']
p_m_ref = syst.struct[0]['p_m']

# Calculate initial references
events=[{'P_t':0.0, 'Q_t':0.0}]
syst.initialize(events,xy0=1.0)
x_0 = np.copy(syst.struct[0].x)
v_f_0 = syst.get_value('v_f')
p_m_0 = syst.get_value('p_m')

# Control design
ssa.eval_ss(syst)
Q = np.eye(syst.N_x)*100
R = np.eye(syst.N_u)

K = ctrl.place(syst.A,syst.B,[-2.0+1j*6,-2.0-1j*6,-100,-101])
K,S,E = ctrl.lqr(syst.A,syst.B,Q,R)
Ad,Bd = ssa.discretise_time(syst.A,syst.B,Ts_control)
Kd,S,E = ssa.dlqr(Ad,Bd,Q,R)

for t in times:
    
    x = np.copy(syst.struct[0].x)
    v_f = v_f_0 
    p_m = p_m_0 

    if t>1.0: 
        u_ctrl = K*(x_ref - x)
        p_m = p_m_ref + u_ctrl[0]
        v_f = v_f_ref + u_ctrl[1]
        
        
    events=[{'t_end':t,'v_f':v_f,'p_m':p_m}]
    syst.run(events)

syst.post();
    

ValueError: at least one of the requested pole is repeated more than rank(B) times

In [15]:
ssa.eval_ss(syst)


array([[ 0.00000000e+00,  3.14159265e+02,  0.00000000e+00,
         0.00000000e+00],
       [-3.54343376e-01, -1.42857143e-01, -3.57095245e-01,
         1.00330478e-01],
       [-4.67038328e-01,  0.00000000e+00, -6.64265905e-01,
        -2.31113959e-03],
       [ 7.98653399e-01,  0.00000000e+00,  1.35913375e-02,
        -2.58565604e+00]])

In [33]:
from scipy.signal import ss2tf,lti,bode

In [37]:
num,den =ss2tf(syst.A,syst.B,syst.C,syst.D,input=0)

In [38]:
G = lti(num[1],den)

C:\programdata\anaconda3\lib\site-packages\scipy\signal\filter_design.py:1622: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)


In [39]:
w, mag, phase = G.bode()
plt.figure()
plt.semilogx(w, mag)    # Bode magnitude plot
plt.figure()
plt.semilogx(w, phase)  # Bode phase plot
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
events=[{'t_end':1.0,'P_t':0.8, 'Q_t':0.5},
        {'t_end':10.0, 'p_m':0.9}
       ]

syst.simulate(events,xy0=1.0);

In [20]:
syst.inputs_run_list


['p_m', 'v_f']

In [43]:
0.01/6

0.0016666666666666668

In [28]:
syst.B

array([[0.        , 0.        ],
       [0.14285714, 0.        ],
       [0.        , 0.125     ],
       [0.        , 0.        ]])

In [30]:
syst.struct[0]['Fu']

array([[0.        , 0.        ],
       [0.14285714, 0.        ],
       [0.        , 0.125     ],
       [0.        , 0.        ]])