In [17]:
%matplotlib widget

In [18]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sopt

In [19]:
from imib_fisix_3ord import imib_fisix_3ord_class

In [20]:
syst = imib_fisix_3ord_class()

In [21]:
xy0 = np.zeros(syst.N_x+syst.N_y)+1.0
#syst.struct[0].tau_m = 0.1
xy = sopt.root(syst.ini_problem,xy0,jac=syst.ini_dae_jacobian,method='hybr')
#syst.struct[0].y_ini[syst.y_ini_list.index('tau_m')]
#syst.struct[0].y_ini[syst.y_ini_list.index('Q_c')]
print(xy.success)
xy.x

True


array([ 1.00145279,  0.97825508, -0.01766518,  1.00129932, -0.00110694,
        0.47203419,  0.10236273, -0.00190102, -0.10527384,  0.20316353,
        0.47254602,  0.9999875 ,  0.00500008])

In [22]:
t_sc = 1.6
events = [{'t_end':1.0, 'P_h':1, 'Q_h':0, 'D':0.0, 'v_0':1, 'X_l':0.05, 'Dt':0.001},
          {'t_end':t_sc,      'v_0':0.05,  'Dt':0.0001},
          {'t_end':t_sc+.001, 'v_0':0.07},
          {'t_end':t_sc+.002, 'v_0':0.1},
          {'t_end':t_sc+.003, 'v_0':0.2},
          {'t_end':t_sc+.004, 'v_0':0.3},
          {'t_end':t_sc+.005, 'v_0':0.5},
          {'t_end':t_sc+.006, 'v_0':0.6},
          {'t_end':t_sc+.007, 'v_0':0.7},
          {'t_end':t_sc+.008, 'v_0':0.8},
          {'t_end':t_sc+.009, 'v_0':0.9},
          {'t_end':t_sc+5, 'v_0':1.0,  'Dt':0.001}]
events = [{'t_end':1.0, 'P_h':0.1, 'Q_h':0, 'D':0.0, 'v_0':1, 'X_l':0.05, 'Dt':0.01},
          {'t_end':10.0,'tau_m':0.2}]
syst.simulate(events,xy0=1)
fig, axes = plt.subplots(nrows=3, ncols=1, figsize=(7, 4), sharex = True)
axes[0].plot(syst.T, syst.X[:,syst.x_list.index('omega_e')])
axes[1].plot(syst.T, syst.Y[:,syst.y_list.index('P_h')])
axes[1].plot(syst.T, syst.Y[:,syst.y_list.index('Q_h')])
axes[2].plot(syst.T, abs(syst.Y[:,syst.y_list.index('v_h')]))
#axes[2].plot(syst.T, syst.Z[:,2])


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
syst.Z[:,0]

array([62.74426738, 62.74426738, 62.74426738, 62.74426738, 62.74426738,
       62.74426738, 62.74426738, 62.74426738, 62.74426738, 62.74426738,
       62.74426738, 62.80180687, 65.18274462, 66.75665092, 67.12208392,
       67.18055217, 67.18766513, 67.18823995, 67.18823484, 67.18822171,
       67.18821758, 67.18821683, 67.18821672, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18821671,
       67.18821671, 67.18821671, 67.18821671, 67.18821671, 67.18

In [16]:
syst.struct.tau_m

array([0.2])