In [1]:
%matplotlib widget

In [2]:
from cigre_eu_mv import cigre_eu_mv_class
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sopt
import ipywidgets
from pydae import ssa

In [13]:
syst = cigre_eu_mv_class()
syst.Dt = 10000e-6
syst.decimation = 1
syst.N_store = 100_000
syst.update()

In [14]:
syst.sopt_root_jac = False
events = [{'t_end':0.01}]

syst.initialize(events,xy0=10e3)


(array([], shape=(0, 1), dtype=float64),
 array([], shape=(0, 1), dtype=float64),
 array([], shape=(0, 44), dtype=float64),
 array([], shape=(0, 1), dtype=float64))

In [15]:
for item in syst.x_list:
    print(f'{item:8s} = {syst.get_value(item):8.2f}')

a        =     1.00


In [16]:
events = [{'t_end':0.001,  'i_11_Q':0.0},
          {'t_end':0.1,  'i_11_Q':100.0},]
syst.simulate(events,xy0=20e3);

In [17]:
plt.close('all')
fig, axes = plt.subplots(nrows=2,ncols=2, figsize=(10, 5), frameon=False, dpi=80)

axes[0,0].plot(syst.T, syst.get_values('v_10_D'), label=f"Bus 10: $v_D$")
axes[0,0].plot(syst.T, syst.get_values('v_10_Q'), label=f"Bus 10: $v_Q$")
axes[0,1].plot(syst.T, syst.get_values('i_l_1011_D'), label=f"Line 10-11: $i_D$")
axes[0,1].plot(syst.T, syst.get_values('i_l_1011_Q'), label=f"Line 10-11: $i_Q$")
#axes[1,1].plot(times,X_obs[:,0] + x_d_0[0],   label=f'$X_obs$')
for ax in axes.flatten():
    ax.legend(loc='best')
    ax.grid(True)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

No handles with labels found to put in legend.
No handles with labels found to put in legend.


In [24]:
Dt =  0.010943-0.0110609
1/Dt*5

-42408.821034775

In [27]:
ssa.eval_A(syst)
ssa.damp_report(syst)

Real          Imag         Freq.          Damp
Mode 1  -219.823732  2.268971e+08  3.611180e+07  9.688255e-07
Mode 2  -219.823732 -2.268971e+08  3.611180e+07  9.688255e-07
Mode 3  -219.823732  9.305037e+07  1.480943e+07  2.362416e-06
Mode 4  -219.823732 -9.305037e+07  1.480943e+07  2.362416e-06
Mode 5  -219.823732  8.976128e+07  1.428595e+07  2.448982e-06
Mode 6  -219.823732 -8.976128e+07  1.428595e+07  2.448982e-06
Mode 7  -219.823732  6.602944e+07  1.050891e+07  3.329177e-06
Mode 8  -219.823732 -6.602944e+07  1.050891e+07  3.329177e-06
Mode 9  -219.823732  2.047996e+07  3.259488e+06  1.073360e-05
Mode 10 -219.823732 -2.047996e+07  3.259488e+06  1.073360e-05
Mode 11 -219.823732  1.479324e+07  2.354417e+06  1.485975e-05
Mode 12 -219.823732 -1.479324e+07  2.354417e+06  1.485975e-05
Mode 13 -219.823732  5.914235e+06  9.412797e+05  3.716858e-05
Mode 14 -219.823732 -5.914235e+06  9.412797e+05  3.716858e-05
Mode 15 -219.823732  4.832594e+06  7.691312e+05  4.548773e-05
Mode 16 -219.823732 -4.832594e+06  7.691312e+05  4.548773e-05
Mode 17 -219.823732  1.511013e+06  2.404852e+05  1.454810e-04
Mode 18 -219.823732 -1.511013e+06  2.404852e+05  1.454810e-04
Mode 19 -219.823732  1.207881e+05  1.922402e+04  1.819909e-03
Mode 20 -219.823732 -1.207881e+05  1.922402e+04  1.819909e-03
Mode 21 -219.823732  3.141593e+02  5.000000e+01  5.733087e-01
Mode 22 -219.823732 -3.141593e+02  5.000000e+01  5.733087e-01

In [14]:
ssa.participation(syst).abs().round(2)

Mode 1  Mode 2  Mode 3  Mode 4  Mode 5  Mode 6  Mode 7  Mode 8  \
i_l_0102_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0102_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0203_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0203_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0304_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0304_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0308_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0308_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0405_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0405_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0506_D    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0506_Q    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
i_l_0607_D    0.00    0.00    0.00    0.00    0.04    0.04    0.04    0.04   
i_l_0607_Q    0.00    0.00    0.00    0.00    0.04    0.04    0.04    0.04   
i_l_0708_D    0.00    0.00    0.00    0.00    0.01    0.01    0.01    0.01   
i_l_0708_Q    0.00    0.00    0.00    0.00    0.01    0.01    0.01    0.01   
i_l_0809_D    0.00    0.00    0.00    0.00    0.15    0.15    0.15    0.15   
i_l_0809_Q    0.00    0.00    0.00    0.00    0.15    0.15    0.15    0.15   
i_l_0910_D    0.01    0.01    0.01    0.01    0.05    0.05    0.05    0.05   
i_l_0910_Q    0.01    0.01    0.01    0.01    0.05    0.05    0.05    0.05   
i_l_1011_D    0.24    0.24    0.24    0.24    0.00    0.00    0.00    0.00   
i_l_1011_Q    0.24    0.24    0.24    0.24    0.00    0.00    0.00    0.00   
v_02_D        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_02_Q        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_03_D        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_03_Q        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_04_D        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_04_Q        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_05_D        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_05_Q        0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
v_06_D        0.00    0.00    0.00    0.00    0.02    0.02    0.02    0.02   
v_06_Q        0.00    0.00    0.00    0.00    0.02    0.02    0.02    0.02   
v_07_D        0.00    0.00    0.00    0.00    0.02    0.02    0.02    0.02   
v_07_Q        0.00    0.00    0.00    0.00    0.02    0.02    0.02    0.02   
v_08_D        0.00    0.00    0.00    0.00    0.04    0.04    0.04    0.04   
v_08_Q        0.00    0.00    0.00    0.00    0.04    0.04    0.04    0.04   
v_09_D        0.00    0.00    0.00    0.00    0.16    0.16    0.16    0.16   
v_09_Q        0.00    0.00    0.00    0.00    0.16    0.16    0.16    0.16   
v_10_D        0.07    0.07    0.07    0.07    0.00    0.00    0.00    0.00   
v_10_Q        0.07    0.07    0.07    0.07    0.00    0.00    0.00    0.00   
v_11_D        0.18    0.18    0.18    0.18    0.01    0.01    0.01    0.01   
v_11_Q        0.18    0.18    0.18    0.18    0.01    0.01    0.01    0.01   

            Mode 9  Mode 10  ...  Mode 33  Mode 34  Mode 35  Mode 36  Mode 37  \
i_l_0102_D    0.00     0.00  ...     0.14     0.14     0.14     0.14     0.11   
i_l_0102_Q    0.00     0.00  ...     0.14     0.14     0.14     0.14     0.11   
i_l_0203_D    0.00     0.00  ...     0.10     0.10     0.10     0.10     0.13   
i_l_0203_Q    0.00     0.00  ...     0.10     0.10     0.10     0.10     0.13   
i_l_0304_D    0.00     0.00  ...     0.00     0.00     0.00     0.00     0.00   
i_l_0304_Q    0.00     0.00  ...     0.00     0.00     0.00     0.00     0.00   
i_l_0308_D    0.00     0.00  ...     0.01     0.01     0.01     0.01     0.01   
i_l_0308_

In [9]:
ssa.eval_A(syst)
ssa.damp_report(syst)

Real           Imag         Freq.      Damp
Mode 1  -109.911866  267300.914640  42542.261858  0.000411
Mode 2  -109.911866 -267300.914640  42542.261858  0.000411
Mode 3  -109.911866  266672.596109  42442.261858  0.000412
Mode 4  -109.911866 -266672.596109  42442.261858  0.000412
Mode 5  -109.911866  171289.955698  27261.643151  0.000642
Mode 6  -109.911866 -171289.955698  27261.643151  0.000642
Mode 7  -109.911866  170661.637167  27161.643151  0.000644
Mode 8  -109.911866 -170661.637167  27161.643151  0.000644
Mode 9  -109.911866  168240.997918  26776.386449  0.000653
Mode 10 -109.911866 -168240.997918  26776.386449  0.000653
Mode 11 -109.911866  167612.679387  26676.386449  0.000656
Mode 12 -109.911866 -167612.679387  26676.386449  0.000656
Mode 13 -109.911866  143713.087982  22872.648339  0.000765
Mode 14 -109.911866 -143713.087982  22872.648339  0.000765
Mode 15 -109.911866  144341.406512  22972.648339  0.000761
Mode 16 -109.911866 -144341.406512  22972.648339  0.000761
Mode 17 -109.911866   80526.735016  12816.227929  0.001365
Mode 18 -109.911866  -80526.735016  12816.227929  0.001365
Mode 19 -109.911866   79898.416485  12716.227929  0.001376
Mode 20 -109.911866  -79898.416485  12716.227929  0.001376
Mode 21 -109.911866   68486.872246  10900.024255  0.001605
Mode 22 -109.911866  -68486.872246  10900.024255  0.001605
Mode 23 -109.911866   67858.553715  10800.024255  0.001620
Mode 24 -109.911866  -67858.553715  10800.024255  0.001620
Mode 25 -109.911866   43419.822844   6910.479434  0.002531
Mode 26 -109.911866  -43419.822844   6910.479434  0.002531
Mode 27 -109.911866   42791.504314   6810.479434  0.002569
Mode 28 -109.911866  -42791.504314   6810.479434  0.002569
Mode 29 -109.911866   39279.409641   6251.512206  0.002798
Mode 30 -109.911866  -39279.409641   6251.512206  0.002798
Mode 31 -109.911866   38651.091110   6151.512206  0.002844
Mode 32 -109.911866  -38651.091110   6151.512206  0.002844
Mode 33 -109.911866   22103.729803   3517.917859  0.004972
Mode 34 -109.911866  -22103.729803   3517.917859  0.004972
Mode 35 -109.911866   21475.411273   3417.917859  0.005118
Mode 36 -109.911866  -21475.411273   3417.917859  0.005118
Mode 37 -109.911866    6481.274961   1031.526948  0.016956
Mode 38 -109.911866   -6481.274961   1031.526948  0.016956
Mode 39 -109.911866    5852.956431    931.526948  0.018776
Mode 40 -109.911866   -5852.956431    931.526948  0.018776
Mode 41 -219.823732     314.159265     50.000000  0.573309
Mode 42 -219.823732    -314.159265     50.000000  0.573309

In [10]:
for item in syst.params_list:
    print(f'{item:8s} = {syst.get_value(item)}')

R_0102   = 1.41282
L_0102   = 0.0064270585739141526
C_0102   = 4.2631325817165496e-07
R_0203   = 2.21442
L_0203   = 0.01007361663003566
C_0203   = 6.681931209640832e-07
R_0304   = 0.30561
L_0304   = 0.001390250258896324
C_0304   = 9.22166976896133e-08
R_0308   = 0.6513
L_0308   = 0.0029628284205987236
C_0308   = 1.96527388518848e-07
R_0405   = 0.28056000000000003
L_0405   = 0.0012762953196425273
C_0405   = 8.465795197734993e-08
R_0506   = 0.77154
L_0506   = 0.0035098121290169496
C_0506   = 2.3280936793771228e-07
R_0607   = 0.12024
L_0607   = 0.0005469837084182259
C_0607   = 3.628197941886425e-08
R_0708   = 0.8366699999999999
L_0708   = 0.0038060949710768213
C_0708   = 2.5246210678959706e-07
R_0809   = 0.16032
L_0809   = 0.0007293116112243012
C_0809   = 4.837597255848566e-08
R_0910   = 0.38577
L_0910   = 0.0017549060645084748
C_0910   = 1.1640468396885614e-07
R_1011   = 0.16533
L_1011   = 0.0007521025990750605
C_1011   = 4.988772170093834e-08
i_02_D   = 0.0
i_02_Q   = 0.0
i_03_D   = 0.0

In [8]:
L_1314 = syst.get_value('L_1314')
C_1314 = syst.get_value('C_1314')

In [9]:
1/np.sqrt(L_1314*C_1314)

18018.03272678112

In [11]:
syst.struct.f

array([[[0.00000000e+00],
        [0.00000000e+00],
        [2.60672895e-13],
        [0.00000000e+00],
        [0.00000000e+00],
        [7.28105500e-13],
        [0.00000000e+00],
        [0.00000000e+00],
        [4.08406201e-18],
        [4.08406203e-18],
        [4.08406201e-18],
        [4.08406201e-18],
        [4.08406202e-18],
        [4.08406202e-18]]])

In [7]:
np.linalg.eig(syst.A)

(array([-109.91186588+31014.74264123j, -109.91186588-31014.74264123j,
        -109.91186588+30386.42411052j, -109.91186588-30386.42411052j,
        -109.91186588+10500.62896241j, -109.91186588-10500.62896241j,
        -109.91186588 +9872.3104317j , -109.91186588 -9872.3104317j ]),
 array([[-8.50593133e-04-3.04522807e-06j, -8.50593133e-04+3.04522807e-06j,
         -3.04522807e-06+8.50593133e-04j, -3.04522807e-06-8.50593133e-04j,
         -4.00611925e-03-4.32259708e-05j, -4.00611925e-03+4.32259708e-05j,
          4.00611925e-03+4.32259708e-05j,  4.00611925e-03-4.32259708e-05j],
        [-3.04522807e-06+8.50593133e-04j, -3.04522807e-06-8.50593133e-04j,
         -8.50593133e-04-3.04522807e-06j, -8.50593133e-04+3.04522807e-06j,
         -4.32259708e-05+4.00611925e-03j, -4.32259708e-05-4.00611925e-03j,
         -4.32259708e-05+4.00611925e-03j, -4.32259708e-05-4.00611925e-03j],
        [ 4.47133072e-03+1.60079141e-05j,  4.47133072e-03-1.60079141e-05j,
          1.60079141e-05-4.47133072e-03j,