In [1]:
%matplotlib widget

In [2]:
from grid_3bus import grid_3bus_class
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sopt
import ipywidgets
from pydae import ssa

In [3]:
syst = grid_3bus_class()
syst.Dt = 500e-6
syst.decimation = 1
syst.update()

In [4]:
syst.sopt_root_jac = False
events = [{'t_end':0.01}]

syst.initialize(events,xy0=20e3)


(array([], shape=(0, 1), dtype=float64),
 array([], shape=(0, 10), dtype=float64),
 array([], shape=(0, 1), dtype=float64),
 array([], shape=(0, 1), dtype=float64))

In [5]:
for item in syst.x_list:
    print(f'{item:8s} = {syst.get_value(item):8.2f}')

i_l_1213_D =    -0.00
i_l_1213_Q =     0.00
i_l_1314_D =    -0.00
i_l_1314_Q =     0.00
v_12_D   =     0.00
v_12_Q   =    -0.00
v_13_D   =     0.00
v_13_Q   =    -0.00
v_14_D   =     0.00
v_14_Q   =    -0.00


In [6]:
ssa.eval_A(syst)
ssa.damp_report(syst)

Real          Imag        Freq.          Damp
Mode 1  -1.099119e+02  31314.806797  4983.906294  3.509879e-03
Mode 2  -1.099119e+02 -31314.806797  4983.906294  3.509879e-03
Mode 3  -1.099119e+02  30686.488266  4883.906294  3.581745e-03
Mode 4  -1.099119e+02 -30686.488266  4883.906294  3.581745e-03
Mode 5  -1.099119e+02  17796.763273  2832.442846  6.175829e-03
Mode 6  -1.099119e+02 -17796.763273  2832.442846  6.175829e-03
Mode 7  -1.099119e+02  18425.081804  2932.442846  5.965233e-03
Mode 8  -1.099119e+02 -18425.081804  2932.442846  5.965233e-03
Mode 9  -1.785239e-13    314.159265    50.000000  5.682591e-16
Mode 10 -1.785239e-13   -314.159265    50.000000  5.682591e-16

In [7]:
ssa.eval_A(syst)
ssa.damp_report(syst)

Real          Imag        Freq.          Damp
Mode 1  -1.099119e+02  31314.806797  4983.906294  3.509879e-03
Mode 2  -1.099119e+02 -31314.806797  4983.906294  3.509879e-03
Mode 3  -1.099119e+02  30686.488266  4883.906294  3.581745e-03
Mode 4  -1.099119e+02 -30686.488266  4883.906294  3.581745e-03
Mode 5  -1.099119e+02  17796.763273  2832.442846  6.175829e-03
Mode 6  -1.099119e+02 -17796.763273  2832.442846  6.175829e-03
Mode 7  -1.099119e+02  18425.081804  2932.442846  5.965233e-03
Mode 8  -1.099119e+02 -18425.081804  2932.442846  5.965233e-03
Mode 9  -1.785239e-13    314.159265    50.000000  5.682591e-16
Mode 10 -1.785239e-13   -314.159265    50.000000  5.682591e-16

In [8]:
ssa.eval_A(syst)
ssa.damp_report(syst)

Real          Imag        Freq.          Damp
Mode 1  -1.099119e+02  31314.806797  4983.906294  3.509879e-03
Mode 2  -1.099119e+02 -31314.806797  4983.906294  3.509879e-03
Mode 3  -1.099119e+02  30686.488266  4883.906294  3.581745e-03
Mode 4  -1.099119e+02 -30686.488266  4883.906294  3.581745e-03
Mode 5  -1.099119e+02  17796.763273  2832.442846  6.175829e-03
Mode 6  -1.099119e+02 -17796.763273  2832.442846  6.175829e-03
Mode 7  -1.099119e+02  18425.081804  2932.442846  5.965233e-03
Mode 8  -1.099119e+02 -18425.081804  2932.442846  5.965233e-03
Mode 9  -1.785239e-13    314.159265    50.000000  5.682591e-16
Mode 10 -1.785239e-13   -314.159265    50.000000  5.682591e-16

In [9]:
for item in syst.params_list:
    print(f'{item:8s} = {syst.get_value(item)}')

R_1213   = 2.44989
L_1213   = 0.011144793059021352
C_1213   = 7.392453306593591e-07
R_1314   = 1.4979900000000002
L_1314   = 0.006814505367377064
C_1314   = 4.520129935933505e-07
i_12_D   = 0.0
i_12_Q   = 0.0
i_13_D   = 0.0
i_13_Q   = 0.0
i_14_D   = 0.0
i_14_Q   = 0.0
omega    = 314.1592653589793


In [8]:
L_1314 = syst.get_value('L_1314')
C_1314 = syst.get_value('C_1314')

In [9]:
1/np.sqrt(L_1314*C_1314)

18018.03272678112

In [11]:
syst.struct.f

array([[[0.00000000e+00],
        [0.00000000e+00],
        [2.60672895e-13],
        [0.00000000e+00],
        [0.00000000e+00],
        [7.28105500e-13],
        [0.00000000e+00],
        [0.00000000e+00],
        [4.08406201e-18],
        [4.08406203e-18],
        [4.08406201e-18],
        [4.08406201e-18],
        [4.08406202e-18],
        [4.08406202e-18]]])

In [7]:
np.linalg.eig(syst.A)

(array([-109.91186588+31014.74264123j, -109.91186588-31014.74264123j,
        -109.91186588+30386.42411052j, -109.91186588-30386.42411052j,
        -109.91186588+10500.62896241j, -109.91186588-10500.62896241j,
        -109.91186588 +9872.3104317j , -109.91186588 -9872.3104317j ]),
 array([[-8.50593133e-04-3.04522807e-06j, -8.50593133e-04+3.04522807e-06j,
         -3.04522807e-06+8.50593133e-04j, -3.04522807e-06-8.50593133e-04j,
         -4.00611925e-03-4.32259708e-05j, -4.00611925e-03+4.32259708e-05j,
          4.00611925e-03+4.32259708e-05j,  4.00611925e-03-4.32259708e-05j],
        [-3.04522807e-06+8.50593133e-04j, -3.04522807e-06-8.50593133e-04j,
         -8.50593133e-04-3.04522807e-06j, -8.50593133e-04+3.04522807e-06j,
         -4.32259708e-05+4.00611925e-03j, -4.32259708e-05-4.00611925e-03j,
         -4.32259708e-05+4.00611925e-03j, -4.32259708e-05-4.00611925e-03j],
        [ 4.47133072e-03+1.60079141e-05j,  4.47133072e-03-1.60079141e-05j,
          1.60079141e-05-4.47133072e-03j,