# SMIB system as in Milano's book example 8.1

In [1]:
%matplotlib widget

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as sopt
import ipywidgets
from pydae import ssa
import json

## Import system module

In [3]:
from smib_milano_ex8p1_4ord_avr import smib_milano_ex8p1_4ord_avr_class

## Instantiate system

In [4]:
syst = smib_milano_ex8p1_4ord_avr_class()


## Initialize the system (backward and foreward)

In [5]:
events=[{'p_t':0.8, 'v_t':1.1, 'K_a':500, 'T_e':0.1}]
syst.initialize(events,xy0=1)

syst.save_0()
syst.report_u()
syst.report_x()
syst.report_y()

p_m   =  0.80
v_ref =  1.11
delta =  0.49
omega =  1.00
e1q   =  1.38
e1d   =  0.28
v_c   =  1.10
v_d   =  0.44
v_q   =  1.01
i_d   =  1.23
i_q   =  0.25
p_e   =  0.80
p_t   =  0.80
q_t   =  1.13
v_t   =  1.10
theta_t =  0.07
v_f   =  3.24


## Simulation

In [99]:
syst = smib_milano_ex8p1_4ord_avr_class()


events=[{'p_t':0.8, 'v_t':1.0, 'K_a':400, 'T_e':0.5, 'H':6}]
syst.initialize(events,xy0=1)

events=[{'t_end':1.0},
        {'t_end':15.0, 'p_m':0.8, 'v_ref':1.05}
       ]

syst.simulate(events,xy0='prev');

In [100]:
plt.close('all')
fig, axes = plt.subplots(nrows=2,ncols=2, figsize=(10, 5), frameon=False, dpi=50)

axes[0,0].plot(syst.T, syst.get_values('omega'), label=f'$\omega$')
axes[0,1].plot(syst.T, syst.get_values('v_t'),   label=f'$v_t$')
axes[1,0].plot(syst.T, syst.get_values('p_t'),   label=f'$p_t$')
axes[1,1].plot(syst.T, syst.get_values('q_t'),   label=f'$q_t$')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Run in two time intervals

In [101]:
events=[{'t_end':1.0}]
syst.run(events)
events=[{'t_end':2.0}]
syst.run(events)

1

In [102]:
syst.get_value('omega')

1.000058557546387

In [6]:
events=[{'p_t':0.8, 'v_t':1.0, 'K_a':400, 'T_e':0.5}]
syst.initialize(events,xy0=1)
ssa.eval_A(syst)
ssa.damp_report(syst)

Real      Imag     Freq.      Damp
Mode 1 -0.301684  9.727972  1.548255  0.030997
Mode 2 -0.301684 -9.727972  1.548255  0.030997
Mode 3 -1.715734  0.000000  0.000000  1.000000
Mode 4 -1.378857  3.840144  0.611178  0.337940
Mode 5 -1.378857 -3.840144  0.611178  0.337940

In [104]:
syst.get_value('p_m')

0.8019231311057791

In [21]:
Ts_control = 0.010
times = np.arange(0.0,10,Ts_control)

# Calculate second references
events=[{'P_t':0.9, 'Q_t':0.0}]
syst.initialize(events,xy0=1.0)
x_ref = np.copy(syst.struct[0].x)
v_f_ref = syst.struct[0]['v_f']
p_m_ref = syst.struct[0]['p_m']

# Calculate initial references
events=[{'P_t':0.0, 'Q_t':0.0}]
syst.initialize(events,xy0=1.0)
x_0 = np.copy(syst.struct[0].x)
v_f_0 = syst.get_value('v_f')
p_m_0 = syst.get_value('p_m')

# Control design
ssa.eval_ss(syst)
Q = np.eye(syst.N_x)*100
R = np.eye(syst.N_u)

K = ctrl.place(syst.A,syst.B,[-2.0+1j*6,-2.0-1j*6,-100,-101])
K,S,E = ctrl.lqr(syst.A,syst.B,Q,R)
Ad,Bd = ssa.discretise_time(syst.A,syst.B,Ts_control)
Kd,S,E = ssa.dlqr(Ad,Bd,Q,R)

for t in times:
    
    x = np.copy(syst.struct[0].x)
    v_f = v_f_0 
    p_m = p_m_0 

    if t>1.0: 
        u_ctrl = K*(x_ref - x)
        p_m = p_m_ref + u_ctrl[0]
        v_f = v_f_ref + u_ctrl[1]
        
        
    events=[{'t_end':t,'v_f':v_f,'p_m':p_m}]
    syst.run(events)

syst.post();
    

ValueError: at least one of the requested pole is repeated more than rank(B) times

In [ ]:
plt.close('all')
fig, axes = plt.subplots(nrows=2,ncols=2, figsize=(10, 5), frameon=False, dpi=50)

axes[0,0].plot(syst.T, syst.get_values('omega'), label=f'$\omega$')
axes[0,1].plot(syst.T, syst.get_values('v_1'),   label=f'$v_1$')
axes[1,0].plot(syst.T, syst.get_values('P_t'),   label=f'$P_t$')
axes[1,1].plot(syst.T, syst.get_values('Q_t'),   label=f'$Q_t$')

In [15]:
ssa.eval_ss(syst)


array([[ 0.00000000e+00,  3.14159265e+02,  0.00000000e+00,
         0.00000000e+00],
       [-3.54343376e-01, -1.42857143e-01, -3.57095245e-01,
         1.00330478e-01],
       [-4.67038328e-01,  0.00000000e+00, -6.64265905e-01,
        -2.31113959e-03],
       [ 7.98653399e-01,  0.00000000e+00,  1.35913375e-02,
        -2.58565604e+00]])

In [33]:
from scipy.signal import ss2tf,lti,bode

In [37]:
num,den =ss2tf(syst.A,syst.B,syst.C,syst.D,input=0)

In [38]:
G = lti(num[1],den)

C:\programdata\anaconda3\lib\site-packages\scipy\signal\filter_design.py:1622: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)


In [39]:
w, mag, phase = G.bode()
plt.figure()
plt.semilogx(w, mag)    # Bode magnitude plot
plt.figure()
plt.semilogx(w, phase)  # Bode phase plot
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
events=[{'t_end':1.0,'P_t':0.8, 'Q_t':0.5},
        {'t_end':10.0, 'p_m':0.9}
       ]

syst.simulate(events,xy0=1.0);

In [20]:
syst.inputs_run_list


['p_m', 'v_f']

In [43]:
0.01/6

0.0016666666666666668

In [28]:
syst.B

array([[0.        , 0.        ],
       [0.14285714, 0.        ],
       [0.        , 0.125     ],
       [0.        , 0.        ]])

In [30]:
syst.struct[0]['Fu']

array([[0.        , 0.        ],
       [0.14285714, 0.        ],
       [0.        , 0.125     ],
       [0.        , 0.        ]])