In [1]:
import numpy as np
from test import test_class
from pydae import ssa

In [2]:
syst = test_class()
syst.t_end = 30.0
syst.Dt = 0.001
syst.decimation =1
syst.update()


In [3]:
events=[{'u_1':0.1}]
syst.initialization_tol = 1e-6
syst.initialize(events,xy0=100)

syst.initialize(events,xy0=1)
ssa.eval_ss(syst)

A = np.copy(syst.A)
B = np.copy(syst.B)
C = np.copy(syst.C)
D = np.copy(syst.D)
x_0 = np.copy(syst.struct[0].x)
y_0 = np.copy(syst.struct[0].y_run)
u_0 = np.copy(np.array([syst.struct[0].u_1]).reshape(1,1))
z_0 = np.copy(syst.struct.h)

In [4]:
events=[{'u_1':0.11}]
syst.initialization_tol = 1e-6
syst.initialize(events,xy0=100)

syst.initialize(events,xy0=1)


x_1 = np.copy(syst.struct[0].x)
y_1 = np.copy(syst.struct[0].y_run)
u_1 = np.copy(np.array([syst.struct[0].u_1]).reshape(1,1))
z_1 = np.copy(syst.struct.h)

In [5]:
C @ (x_1-x_0) + D @ (u_1 - u_0) + z_0 

array([[[0.012],
        [0.11 ]]])

In [6]:
z_1

array([[[0.0121],
        [0.11  ]]])

In [7]:
syst.struct.h

array([[[10.],
        [ 1.]]])

In [6]:
x

array([[0.46415888]])

In [11]:
A

array([[-1.29266081]])

In [12]:
B

array([[2.]])

In [13]:
C

array([[1.],
       [0.]])

In [14]:
D

array([[0.],
       [0.]])

In [15]:
C * 0 + D*0

array([[0.],
       [0.]])

In [8]:
Hx = syst.struct[0].Hx
Hy = syst.struct[0].Hy
Hu = syst.struct[0].Hu
Gx = syst.struct[0].Gx
Gy = syst.struct[0].Gy
Gu = syst.struct[0].Gu

Hx@x+Hy@y+Hu@u

array([[0.1],
       [0.2],
       [1. ],
       [1. ]])

In [ ]:
C

In [7]:
Hx = syst.struct[0].Hx
Hy = syst.struct[0].Hy
Hu = syst.struct[0].Hu
Gx = syst.struct[0].Gx
Gy = syst.struct[0].Gy
Gu = syst.struct[0].Gu


In [8]:
Hx = syst.struct[0].Hx
Hy = syst.struct[0].Hy
Hu = syst.struct[0].Hu
Gx = syst.struct[0].Gx
Gy = syst.struct[0].Gy
Gu = syst.struct[0].Gu


C_man = Hx - Hy @ np.linalg.solve(Gy,Gx)

In [21]:
Hy @ np.linalg.solve(Gy,Gx)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
y

array([[1.],
       [1.]])

In [15]:
C_man

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [58]:
C @ syst.struct[0].x - syst.struct[0].h

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-3.65212306e-04],
       [ 5.18519951e-01]])

In [59]:
Hx@syst.struct[0].x + Hy@syst.struct[0].y_run

array([[-2.33106054],
       [ 1.        ],
       [ 0.82503045],
       [ 0.00418184],
       [ 0.01690954],
       [ 0.01727475],
       [ 0.00397473]])

In [41]:
Dx = syst.struct[0].x
Du = np.array([syst.struct[0]['p_m_ref'],syst.struct[0]['v_f']]).reshape(2,1)
Dy_man = -np.linalg.solve(Gy,Gx)@Dx - np.linalg.solve(Gy,Gu)@Du

In [42]:
Dy = syst.struct[0].y_run

In [43]:
Dy

array([[1.75999184e-03],
       [9.99998451e-01],
       [1.00000300e-03],
       [1.78499180e-06],
       [9.99998407e-04],
       [2.49999992e-08],
       [5.00000000e-05],
       [1.00000000e-03],
       [1.00000000e+00],
       [1.00000300e-03]])

In [44]:
Dy_man

array([[1.14776660e-03],
       [1.42848942e-01],
       [1.84157789e-02],
       [2.85704437e+00],
       [1.32444638e-02],
       [2.85701574e+00],
       [9.13640906e-04],
       [1.84156688e-02],
       [1.42850741e-01],
       [1.00000300e-03]])

In [45]:
Dy-Dy_man

array([[ 6.12225246e-04],
       [ 8.57149509e-01],
       [-1.74157759e-02],
       [-2.85704258e+00],
       [-1.22444654e-02],
       [-2.85701572e+00],
       [-8.63640906e-04],
       [-1.74156688e-02],
       [ 8.57149259e-01],
       [ 0.00000000e+00]])

In [60]:
np.linalg.solve(Gy,Gu)@Du

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])