In [44]:
import numpy as np
from smib_4ord_ctrl import smib_4ord_ctrl_class
from pydae import ssa


In [45]:
syst = smib_4ord_ctrl_class()
syst.t_end = 1.0
syst.Dt = 0.001
syst.decimation =1
syst.update()


In [60]:
events=[{'t_end':10,'p_t':0.5, 'v_1':1.0}]
syst.initialization_tol = 1e-12
syst.initialize(events,xy0=1)
syst.xy_prev[0]=0
syst.simulate(events,xy0='prev')
ssa.eval_ss(syst)

A = np.copy(syst.A)
B = np.copy(syst.B)
C = np.copy(syst.C)
D = np.copy(syst.D)
x_0 = np.copy(syst.struct[0].x)
y_0 = np.copy(syst.struct[0].y_run)
u_0 = np.array([syst.struct[0]['p_m_ref'],syst.struct[0]['v_f']]).reshape(2,1)
z_0 = np.copy(syst.struct.h)


In [65]:
events=[{'t_end':10,'p_t':0.55, 'v_1':1.0}]
syst.initialization_tol = 1e-12
syst.initialize(events,xy0=1)
syst.xy_prev[0]=0
syst.simulate(events,xy0='prev')

x_1 = np.copy(syst.struct[0].x)
y_1 = np.copy(syst.struct[0].y_run)
u_1 = np.array([syst.struct[0]['p_m_ref'],syst.struct[0]['v_f']]).reshape(2,1)
z_1 = np.copy(syst.struct.h)

In [66]:
C @ (x_1-x_0) + D @ (u_1 - u_0) + z_0

array([[[0.78921134],
        [1.        ],
        [0.84035498],
        [0.43599889],
        [0.55090767],
        [0.55090767],
        [0.54859255]]])

In [67]:
z_1

array([[[0.78921134],
        [1.        ],
        [0.84035498],
        [0.43599889],
        [0.55090767],
        [0.55090767],
        [0.55      ]]])

In [64]:
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
syst.struct[0].h

array([[0.74049023],
       [1.        ],
       [0.85570657],
       [0.41434766],
       [0.50075012],
       [0.50075012],
       [0.5       ]])

In [8]:
Hx = syst.struct[0].Hx
Hy = syst.struct[0].Hy
Hu = syst.struct[0].Hu
Gx = syst.struct[0].Gx
Gy = syst.struct[0].Gy
Gu = syst.struct[0].Gu


C_man = Hx - Hy @ np.linalg.solve(Gy,Gx)

In [9]:
C @ syst.struct[0].x

array([[8.34998951e+00],
       [9.99395831e-01],
       [7.83221877e-01],
       [4.84615703e-03],
       [1.27042121e-02],
       [1.27042121e-02],
       [5.72924843e-18]])

In [43]:
syst.struct[0].x

array([[0.74049023],
       [1.        ],
       [0.85570657],
       [0.41434766],
       [0.50075012]])

In [58]:
C @ syst.struct[0].x - syst.struct[0].h

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [ 0.00000000e+00],
       [-3.65212306e-04],
       [ 5.18519951e-01]])

In [59]:
Hx@syst.struct[0].x + Hy@syst.struct[0].y_run

array([[-2.33106054],
       [ 1.        ],
       [ 0.82503045],
       [ 0.00418184],
       [ 0.01690954],
       [ 0.01727475],
       [ 0.00397473]])

In [41]:
Dx = syst.struct[0].x
Du = np.array([syst.struct[0]['p_m_ref'],syst.struct[0]['v_f']]).reshape(2,1)
Dy_man = -np.linalg.solve(Gy,Gx)@Dx - np.linalg.solve(Gy,Gu)@Du

In [42]:
Dy = syst.struct[0].y_run

In [43]:
Dy

array([[1.75999184e-03],
       [9.99998451e-01],
       [1.00000300e-03],
       [1.78499180e-06],
       [9.99998407e-04],
       [2.49999992e-08],
       [5.00000000e-05],
       [1.00000000e-03],
       [1.00000000e+00],
       [1.00000300e-03]])

In [44]:
Dy_man

array([[1.14776660e-03],
       [1.42848942e-01],
       [1.84157789e-02],
       [2.85704437e+00],
       [1.32444638e-02],
       [2.85701574e+00],
       [9.13640906e-04],
       [1.84156688e-02],
       [1.42850741e-01],
       [1.00000300e-03]])

In [45]:
Dy-Dy_man

array([[ 6.12225246e-04],
       [ 8.57149509e-01],
       [-1.74157759e-02],
       [-2.85704258e+00],
       [-1.22444654e-02],
       [-2.85701572e+00],
       [-8.63640906e-04],
       [-1.74156688e-02],
       [ 8.57149259e-01],
       [ 0.00000000e+00]])

In [60]:
np.linalg.solve(Gy,Gu)@Du

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])